name: Game of Life Workflow

# Run the workflow on every push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Build Debug configuration
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build in Debug configuration
        run: |
          mkdir -p  buid/build-debug
          cd build/build-debug
          cmake -DCMAKE_BUILD_TYPE=Debug ../..
          cmake --build .

  # Step 2: Run tests (only if Debug build succeeded)
  run-tests:
    runs-on: ubuntu-latest
    needs: build-debug
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Run tests in Debug configuration
        run: |
          cd build-debug
          ctest --output-on-failure

  # Step 3: Build in RelWithDebInfo (only if tests passed)
  build-relwithdebinfo:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build in RelWithDebInfo configuration
        run: |
          mkdir build/build-relwithdebinfo
          cd build/build-relwithdebinfo
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ../..
          cmake --build .

  # Step 4: Build Release (only if all previous steps passed)
  build-release:
    runs-on: ubuntu-latest
    needs: build-relwithdebinfo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Build in Release configuration
        run: |
          mkdir build/build-release
          cd build/build-release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
