name: Game of Life Workflow

# Run the workflow on every push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ########################   Unix Pipeline   ###############################

  build-debug-unix:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in Debug configuration with sanitizer
        run: |
          ./build.sh -c Debug  -a 

      - name: Compress build-debug directory into tar.gz
        run: |
          cd build-debug
          rm -rf *_autogen CMakeFies meta_types qmltypes
          cd ..
          tar -czf build-debug-unix.tar.gz build-debug

      - name: Upload build-debug directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-unix.tar.gz
          path: build-debug-unix.tar.gz

  run-tests-unix:
    runs-on: ubuntu-latest
    needs: build-debug-unix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Download build-debug artifact
        uses: actions/download-artifact@v4
        with:
          name: build-debug-unix.tar.gz
          path: .

      - name: Extract the tar.gz file
        run: tar -xzf build-debug-unix.tar.gz

      - name: Run tests in Debug configuration
        run: |
          cd build-debug
          ctest --output-on-failure

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit_report
          path: build-debug/junit_report.xml

      # Generate coverage report using gcovr
      - name: Generate Coverage Report
        run: |
          sudo apt-get install gcovr
          cd build-debug
          mkdir coverage
          gcovr --r .. -e '/.*/(build-debug|tests)/' --html --html-details -o coverage/coverage.html

      # Upload coverage reports as artifacts
      - name: Upload Coverage Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage.html
          path: build-debug/coverage

  static-analysis:
    runs-on: ubuntu-latest
    needs: run-tests-unix
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in Debug configuration with Clang-Tidy checks enabled
        run: |
          ./build.sh -c Debug -s

      # Step 2bis: Memcheck with valgrind
  heap-analysis:
    runs-on: ubuntu-latest
    needs: build-debug-unix
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install valgrind
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind
          pip install ValgrindCI

      - name: Build in Debug configuration without sanitizer
        run: |
          ./build.sh -c Debug

      - name: Run valgrind with memcheck
        run: |
          mkdir valgrind-report
          valgrind --tool=memcheck --xml=yes --xml-file=valgrind-report/heap_analyzis.xml -v --leak-check=full --trace-children=yes --show-reachable=yes --trace-children=yes --track-origins=yes --time-stamp=yes  ./build-debug/GameOfLife --iterations 100 --input tests/Back/input_files/spaceship/rPentomino.txt --all
          valgrind --tool=memcheck  -v --leak-check=full --log-file=valgrind-report/heap_analyzis.valg --trace-children=yes --show-reachable=yes --trace-children=yes --track-origins=yes --time-stamp=yes  ./build-debug/GameOfLife --iterations 100 --input tests/Back/input_files/spaceship/rPentomino.txt --all

      - name: Generate HTML report
        run: |
          cd valgrind-report
          valgrind-ci heap_analyzis.xml --source-dir=../ --output-dir=.

      - name: Upload valgrind report
        uses: actions/upload-artifact@v4
        with:
          name: valgrind-report.zip
          path: valgrind-report

      - name: Check if valgrind found a leak
        run: |
          cd valgrind-report
          valgrind-ci heap_analyzis.xml --abort-on-errors


  build-relwithdebinfo-unix:
    runs-on: ubuntu-latest
    needs: run-tests-unix
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in RelWithDebInfo configuration
        run: |
          ./build.sh -c RelWithDebInfo

      - name: Compress build-relwithdebinfo directory into tar.gz
        run: |
          cd build-relwithdebinfo
          rm -rf *_autogen CMakeFies meta_types qmltypes
          cd ..
          tar -czf build-relwithdebinfo-unix.tar.gz build-relwithdebinfo

      - name: Upload build-relwithdebinfo directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gameOfLife-relwithdebinfo.tar.gz
          path: build-relwithdebinfo-unix.tar.gz

  heap-profiling:
    runs-on: ubuntu-latest
    needs: build-relwithdebinfo-unix
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gperftools
        run: sudo apt-get install google-perftools libunwind-dev libgoogle-perftools-dev

      - name: Build in RelWithDebInfo configuration with Heap profiling
        run: |
          ./build.sh -c RelWithDebInfo -p heap

      - name: HEAP Profiling
        run: |
          ./build-relwithdebinfo/GameOfLife --iterations 100 --input tests/Back/input_files/bigStable.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife heap_profiling.prof* > heap_profiling_bigStable.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife heap_profiling.prof*
          rm heap_profiling.prof*
          ./build-relwithdebinfo/GameOfLife --iterations 100 --input tests/Back/input_files/spaceship/rPentomino.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife heap_profiling.prof* > heap_profiling_pentomino.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife heap_profiling.prof*
          rm heap_profiling.prof*
          ./build-relwithdebinfo/GameOfLife --iterations 100 --input tests/Back/input_files/spaceship/gosperGliderGun.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife heap_profiling.prof* > heap_profiling_gosper.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife heap_profiling.prof*

      - name: Upload profiling reports Big Stable
        uses: actions/upload-artifact@v4
        with:
          name: heap_profiling_bigStable.pdf
          path: heap_profiling_bigStable.pdf

      - name: Upload profiling reports Gosper
        uses: actions/upload-artifact@v4
        with:
          name: heap_profiling_gosper.pdf
          path: heap_profiling_gosper.pdf

      - name: Upload profiling reports Pentomino
        uses: actions/upload-artifact@v4
        with:
          name: heap_profiling_pentomino.pdf
          path: heap_profiling_pentomino.pdf


  cpu-profiling:
    runs-on: ubuntu-latest
    needs: build-relwithdebinfo-unix
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gperftools
        run: sudo apt-get install google-perftools libunwind-dev libgoogle-perftools-dev

      - name: Build in RelWithDebInfo configuration with Heap profiling
        run: |
          ./build.sh -c RelWithDebInfo -p cpu

      # Launch CPU profiling with 1 interrupt every 10µs
      - name: CPU Profiling
        run: |
          CPUPROFILE_FREQUENCY=100000 
          ./build-relwithdebinfo/GameOfLife --iterations 1000 --input tests/Back/input_files/bigStable.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife cpu_profiling.prof > cpu_profiling_bigStable.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife cpu_profiling.prof
          rm cpu_profiling.prof
          ./build-relwithdebinfo/GameOfLife --iterations 1000 --input tests/Back/input_files/spaceship/rPentomino.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife cpu_profiling.prof > cpu_profiling_pentomino.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife cpu_profiling.prof
          rm cpu_profiling.prof
          ./build-relwithdebinfo/GameOfLife --iterations 1000 --input tests/Back/input_files/spaceship/gosperGliderGun.txt --all
          google-pprof --pdf ./build-relwithdebinfo/GameOfLife cpu_profiling.prof > cpu_profiling_gosper.pdf
          google-pprof --text ./build-relwithdebinfo/GameOfLife cpu_profiling.prof

      - name: Upload profiling reports Bit Stable
        uses: actions/upload-artifact@v4
        with:
          name: cpu_rofiling_bigStable.pdf
          path: cpu_profiling_bigStable.pdf

      - name: Upload profiling reports Gosper
        uses: actions/upload-artifact@v4
        with:
          name: cpu_profiling_gosper.pdf
          path: cpu_profiling_gosper.pdf

      - name: Upload profiling reports Pentomino
        uses: actions/upload-artifact@v4
        with:
          name: cpu_profiling_pentomino.pdf
          path: cpu_profiling_pentomino.pdf

  build-release-unix:
    runs-on: ubuntu-latest
    needs: [ heap-analysis, heap-profiling, cpu-profiling, static-analysis ]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in Release configuration
        run: |
          ./build.sh

      - name: Compress build-release directory into tar.gz
        run: |
          cd build-release
          rm -rf *_autogen CMakeFies meta_types qmltypes
          cd ..
          tar -czf build-release-unix.tar.gz build-release

      - name: Upload build-release directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-release-unix.tar.gz
          path: build-release-unix.tar.gz

  ########################   Windows Pipeline   ###############################

  build-debug-windows:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Configure Conan profile
        run: |
          conan profile detect --force

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build in Debug configurations
        shell: pwsh
        run: |
          .\build.ps1 -Config Debug

      - name: Run tests
        run: |
          cd build-debug
          ctest -C Debug --output-on-failure

      - name: Compress build-debug directory into zip
        run: mv build-debug/Debug .

      - name: Upload build directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-windows.zip
          path: Debug

  build-release-windows:
    runs-on: windows-latest
    # needs: build-debug-windows
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          cache: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in Release configuration
        shell: pwsh
        run: |
          .\build.ps1

      - name: Compress build-release directory into zip
        run: mv build-release/Release .

      - name: Package the Release version
        run: |
          windeployqt --qmldir=src/Front/QMLComponents --release Release/appQtGameOfLife.exe

      - name: Upload build-release directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-release-windows.zip
          path: Release